name: trigger the Action in the caller repo
on: workflow_dispatch
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the action in the another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: '${{secrets.REPO_ACCESS_TOKEN}}'
          repository: israr3387/CallerRepo
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }}}'
         
